name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
        cache: 'maven'
    - name: Maven Install
      run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Maven Test
      run: ./mvnw clean test -B -V
    - name: JaCoCo Report
      run: ./mvnw jacoco:report -B -V
