name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: 'maven'
#TODO: figure out this later...
#      - name: Test and deploy to OSSRH
#        run: >-
#          echo "${{ secrets.MAVEN_SETTINGS_XML }}" > settings.xml
#          && mvn
#          -s settings.xml
#          -P release
#          -Dgpg.keyName=${{ secrets.GPG_KEYNAME }}
#          -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
#          clean test deploy
