name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: 'maven'
      - name: Test and deploy to GitHub Packages Maven repo
        run: >-
          echo "${{ secrets.MAVEN_SETTINGS_XML }}" > settings.xml
          && ./mvnw
          -s settings.xml
          -P release
          clean test deploy
