name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: 'maven'
      - name: Test and deploy to GitHub Packages Maven repo
        run: ./mvnw --batch-mode -P release clean test deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
